### ISSUE TITLE
failed to call read_rs balance

### ISSUE THREAD

**Issue by LevenSton** [dfinance-tech/read_rs#1]
i install the read_rs canister in mainnet,  call balance interface failed,

$ ADMIN_ACCOUNT=\"$(dfx ledger account-id)\"
$ dfx canister --no-wallet --network ic call read_rs balance "(record { account=$ADMIN_ACCOUNT})"
The Replica returned an error: code 5, message: "IC0503: Canister ywrdt-7aaaa-aaaah-qaaaa-cai trapped explicitly: Panicked at 'called `Result::unwrap()` on an `Err` value: (Some(3), "Canister ryjl3-tyaaa-aaaaa-aaaba-cai not found")', src/main.rs:92:12"

can you give some hint? thks

**Comment by flyq** [comment]
Yes, There are still some problems need to be savled. It worked well in local env, but not in the mainnet.
Maybe:
1. inter-subnet call not allowed.
2. Rust canister need do more in code.

So I'll try Rust/Motoko initer-subnet call. I'll update here while any new info.

**Comment by flyq** [comment]
This fixed in https://github.com/dfinance-tech/read_rs/commit/79bb17987b5843abc182a83649ee835da31f5cd1 , I closed it.
